export { default as Main } from "./Main/Main";
export { default as Header } from "./Header/Header";
export { default as Login } from "./Login/Login";
export { default as Posts } from "./Posts/Posts";
export { default as Post } from "./Post/Post";
export { default as Panel } from "./Panel/Panel";
export { default as Board } from "./Board/Board";
export { default as Comment } from "./Comment/Comment";
export { default as AddComment } from "./AddComment/AddComment";
